
name: mib3
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in: ^6.3.0
  sqflite:
  get:
  path:
  drift:
  drift_flutter:
  sqlite3_flutter_libs:
  path_provider:
  uuid:
  flutter_styled_toast:
  intl:
  table_calendar:
  window_size:

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons:
  drift_dev:
  build_runner:


flutter:
  uses-material-design: true

  assets:
    - assets/font/

  fonts:
    - family: OpenSans-Medium
      fonts:
        - asset: assets/font/OpenSans-Medium.ttf
    - family: D2Coding-Ver1.3.2-20180524
      fonts:
        - asset: assets/font/D2Coding-Ver1.3.2-20180524.ttf
    - family: SeoulHangangM
      fonts:
        - asset: assets/font/SeoulHangangM.ttf
    - family: 경기천년제목_Light
      fonts:
        - asset: assets/font/경기천년제목_Light.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png

flutter_icons:
  android: false
  ios: false
  macos:
    generate: true
  image_path: "assets/icon/app_icon.png"